{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Changes occuring in the provision Structured Medications Reviews (SMRs): 09/2020 - 01/2021 \n",
    "\n",
    "Below are various time-series graphs showing changes in total nationwide SMR provision as well as a breakdown by region and other demographic variables.  The following graphs are available:\n",
    "* [Total SMR number](#total-smr)\n",
    "* [Decile chart of rate of SMR by practice](#decile-smr)\n",
    "* [Rate of SMR by geographical region](#smr-region)\n",
    "* [Rate of SMR by age group](#smr-age)\n",
    "* [Rate of SMR by sex](#smr-sex)\n",
    "* [Rate of SMR by care home status](#smr-care-home)\n",
    "* [Rate of SMR by recent hospital admission status](#smr-hospital-admission)\n",
    "* [Rate of SMR by recent falls status](#smr-falls)\n",
    "\n",
    "\n",
    "#### Methods\n",
    "Using OpenSAFELY-TPP, covering 40% of England's population, we have assessed coding activity related to SMR in general practice from the beginning of September 2020 until the end of Januray 2021. The codelist used can be found here at [OpenSAFELY Codelists](https://codelists.opensafely.org/codelist/opensafely/structured-medication-review-nhs-england/5459205f/#full-list).  For each within the study period, we have calculated the rate at which the code was recorded per 1000 registered patients.\n",
    "\n",
    "All analytical code and output is available for inspection at the [OpenSAFELY GitHub repository](https://github.com/opensafely/SRO-smr)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       " <style>\n",
       ".output_png {\n",
       "    display: table-cell;\n",
       "    text-align: center;\n",
       "    vertical-align: middle;\n",
       "}\n",
       "</style> "
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from IPython.display import HTML\n",
    "from IPython.core.display import HTML as Center\n",
    "\n",
    "Center(\"\"\" <style>\n",
    ".output_png {\n",
    "    display: table-cell;\n",
    "    text-align: center;\n",
    "    vertical-align: middle;\n",
    "}\n",
    "</style> \"\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'ebmdatalab'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-2-9d6d7fce0877>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mmatplotlib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpyplot\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mplt\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mos\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 6\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0mebmdatalab\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mcharts\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      7\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mpandas\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mplotting\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mregister_matplotlib_converters\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      8\u001b[0m \u001b[0mregister_matplotlib_converters\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'ebmdatalab'"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import os\n",
    "from ebmdatalab import charts\n",
    "from pandas.plotting import register_matplotlib_converters\n",
    "register_matplotlib_converters()\n",
    "\n",
    "%matplotlib inline\n",
    "\n",
    "\n",
    "class Measure:\n",
    "  def __init__(self, id, numerator, denominator, group_by):\n",
    "    self.id = id\n",
    "    self.numerator = numerator\n",
    "    self.denominator = denominator\n",
    "    self.group_by = group_by\n",
    "\n",
    "measures = [\n",
    "    Measure(\n",
    "        id=\"smr_by_sex\",\n",
    "        numerator=\"had_smr\",\n",
    "        denominator=\"population\",\n",
    "        group_by=[\"sex\"],\n",
    "    ),\n",
    "\n",
    "    Measure(\n",
    "        id=\"smr_by_region\",\n",
    "        numerator=\"had_smr\",\n",
    "        denominator=\"population\",\n",
    "        group_by=[\"region\"],\n",
    "    ),\n",
    "\n",
    "    Measure(\n",
    "        id=\"smr_by_age_band\",\n",
    "        numerator=\"had_smr\",\n",
    "        denominator=\"population\",\n",
    "        group_by=[\"age_band\"],\n",
    "    ),\n",
    "\n",
    "    Measure(\n",
    "        id=\"smr_by_care_home_status\",\n",
    "        numerator=\"had_smr\",\n",
    "        denominator=\"population\",\n",
    "        group_by=[\"care_home_status\"],\n",
    "    ),\n",
    "\n",
    "    Measure(\n",
    "        id=\"smr_by_falls\",\n",
    "        numerator=\"had_smr\",\n",
    "        denominator=\"population\",\n",
    "        group_by=[\"recent_falls\"],\n",
    "    ),\n",
    "\n",
    "    Measure(\n",
    "        id=\"smr_by_hospital_admission\",\n",
    "        numerator=\"had_smr\",\n",
    "        denominator=\"population\",\n",
    "        group_by=[\"recent_hospital_admission\"],\n",
    "    ),\n",
    "\n",
    "    Measure(\n",
    "        id=\"smr_total\",\n",
    "        numerator=\"had_smr\",\n",
    "        denominator=\"population\",\n",
    "        group_by=None,\n",
    "    ),\n",
    "\n",
    "    Measure(\n",
    "        id=\"smr_total_by_practice\",\n",
    "        numerator=\"had_smr\",\n",
    "        denominator=\"population\",\n",
    "        group_by=[\"practice\"],\n",
    "    ),\n",
    "]\n",
    "\n",
    "\n",
    "if not os.path.exists('../output/figures'):\n",
    "    os.mkdir('../output/figures')\n",
    "\n",
    "\n",
    "\n",
    "measures_df_sex = pd.read_csv('../output/measures/measure_smr_by_sex.csv')\n",
    "measures_df_region = pd.read_csv(\n",
    "    '../output/measures/measure_smr_by_region.csv')\n",
    "measures_df_age = pd.read_csv(\n",
    "    '../output/measures/measure_smr_by_age_band.csv')\n",
    "measures_df_falls = pd.read_csv(\n",
    "    '../output/measures/measure_smr_by_falls.csv')\n",
    "measures_df_care_home_status = pd.read_csv(\n",
    "    '../output/measures/measure_smr_by_care_home_status.csv')\n",
    "measures_df_total = pd.read_csv(\n",
    "    '../output/measures/measure_smr_total.csv')\n",
    "measures_df_total_by_practice = pd.read_csv(\n",
    "    '../output/measures/measure_smr_total_by_practice.csv')\n",
    "measures_df_hospital_admission = pd.read_csv(\n",
    "    '../output/measures/measure_smr_by_hospital_admission.csv')\n",
    "\n",
    "# temporary fix for population not working in Measures\n",
    "measures_df_total = measures_df_total.groupby(\n",
    "    ['date'])['had_smr', 'population'].sum().reset_index()\n",
    "measures_df_total['value'] = measures_df_total['had_smr'] / \\\n",
    "    measures_df_total['population']\n",
    "\n",
    "\n",
    "def to_datetime_sort(df):\n",
    "    df['date'] = pd.to_datetime(df['date'])\n",
    "    df.sort_values(by='date', inplace=True)\n",
    "\n",
    "\n",
    "to_datetime_sort(measures_df_sex)\n",
    "to_datetime_sort(measures_df_region)\n",
    "to_datetime_sort(measures_df_age)\n",
    "to_datetime_sort(measures_df_total)\n",
    "to_datetime_sort(measures_df_falls)\n",
    "to_datetime_sort(measures_df_care_home_status)\n",
    "to_datetime_sort(measures_df_total_by_practice)\n",
    "to_datetime_sort(measures_df_hospital_admission)\n",
    "\n",
    "\n",
    "def redact_small_numbers(df, n, m):\n",
    "    \"\"\"\n",
    "    Takes measures df and converts any row to nana where value of denominator or numerater in measure m equal to \n",
    "    or below n\n",
    "    Returns df of same shape.\n",
    "    \"\"\"\n",
    "    mask_n = df[m.numerator].isin(list(range(0, n+1)))\n",
    "    mask_d = df[m.denominator].isin(list(range(0, n+1)))\n",
    "    mask = mask_n | mask_d\n",
    "    df.loc[mask, :] = np.nan\n",
    "    return df\n",
    "\n",
    "redact_small_numbers(measures_df_sex, 10, measures[0])\n",
    "redact_small_numbers(measures_df_region, 10, measures[1])\n",
    "redact_small_numbers(measures_df_age, 10, measures[2])\n",
    "redact_small_numbers(measures_df_care_home_status, 10, measures[3])\n",
    "redact_small_numbers(measures_df_falls, 10, measures[4])\n",
    "redact_small_numbers(measures_df_hospital_admission,\n",
    "                     10, measures[5])\n",
    "redact_small_numbers(measures_df_total,10, measures[6])\n",
    "\n",
    "\n",
    "def calculate_rate(df, value_col='had_smr', population_col='population'):\n",
    "    num_per_thousand = df[value_col]/(df[population_col]/1000)\n",
    "    df['num_per_thousand'] = num_per_thousand\n",
    "\n",
    "\n",
    "calculate_rate(measures_df_sex)\n",
    "calculate_rate(measures_df_age)\n",
    "calculate_rate(measures_df_region)\n",
    "calculate_rate(measures_df_total)\n",
    "calculate_rate(measures_df_falls)\n",
    "calculate_rate(measures_df_care_home_status)\n",
    "calculate_rate(measures_df_total_by_practice)\n",
    "calculate_rate(measures_df_hospital_admission)\n",
    "\n",
    "#https://github.com/opensafely/hospital-disruption-research/blob/master/analysis/rate_calculations.py\n",
    "\n",
    "\n",
    "#Remove U/T in sex column\n",
    "measures_df_sex = measures_df_sex[measures_df_sex['sex'].isin([\"F\", \"M\"])]\n",
    "\n",
    "#Remove default age band\n",
    "measures_df_age = measures_df_age[~measures_df_age['age_band'].isin([\"0\"])]\n",
    "\n",
    "def plot_measures(df, title, filename, column_to_plot, category=False, y_label='Rate per 1000'):\n",
    "\n",
    "    if category:\n",
    "        for unique_category in df[category].unique():\n",
    "\n",
    "            df_subset = df[df[category] == unique_category]\n",
    "\n",
    "            plt.plot(df_subset['date'], df_subset[column_to_plot], marker='o');\n",
    "    else:\n",
    "        plt.plot(df['date'], df[column_to_plot], marker='o');\n",
    "\n",
    "    plt.ylabel(y_label)\n",
    "    plt.xlabel('Date')\n",
    "    plt.xticks(rotation='vertical')\n",
    "    plt.title(title)\n",
    "\n",
    "    if category:\n",
    "        plt.legend(df[category].unique(), bbox_to_anchor=(\n",
    "            1.04, 1), loc=\"upper left\")\n",
    "\n",
    "    else:\n",
    "        pass\n",
    "\n",
    "    plt.show()\n",
    "    plt.clf()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<a id='total-smr'></a>\n",
    "## Total SMR Number\n",
    "\n",
    "Total monthly coding activity."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "plot_measures(measures_df_total, 'SMR use across Whole Population',\n",
    "              'population_rates', 'had_smr', category=False, y_label='Total Number')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<a id='decile-smr'></a>\n",
    "## SMR by practice\n",
    "\n",
    "Monthly coding activity rates at the GP practice level.  Each month, the median value and 10-90 percentile activity is shown."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "smr_decile_chart = charts.deciles_chart(\n",
    "    measures_df_total_by_practice,\n",
    "    period_column=\"date\",\n",
    "    column=\"num_per_thousand\",\n",
    "    title=\"SMR by practice\",\n",
    "    ylabel=\"rate per 1000\",\n",
    "    show_outer_percentiles=False,\n",
    "    show_legend=True,\n",
    ");\n",
    "plt.show()\n",
    "plt.clf()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<a id='smr-region'></a>\n",
    "## SMR breakdown by region\n",
    "\n",
    "Monthly coding activity rates by geographical region."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "plot_measures(measures_df_region,\n",
    "              'SMR use by Region per 1000', 'region_rates', 'num_per_thousand', category='region')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<a id='smr-age'></a>\n",
    "## SMR breakdown by age band\n",
    "\n",
    "Monthly coding activity rates by age band."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "plot_measures(measures_df_age,\n",
    "              'SMR use by Age Band per 1000',  'age_rates', 'num_per_thousand', category='age_band')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<a id='smr-sex'></a>\n",
    "## SMR breakdown by sex\n",
    "\n",
    "Monthly coding activity rates by sex."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "plot_measures(measures_df_sex,\n",
    "              'SMR use by Sex per 1000', 'sex_rates', 'num_per_thousand', category='sex', )\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## SMR Priority Variables\n",
    "\n",
    "[This document](https://www.england.nhs.uk/wp-content/uploads/2020/09/SMR-Spec-Guidance-2020-21-FINAL-.pdf) (section 3.1) provides details on those patients that would benefit from SMR and be prioritised.\n",
    "\n",
    "The below charts are a first look at changes in the rate of provision of SMR according to individual priority variables.  These will need to be further developed into \"at risk\" categories."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<a id='smr-care-home'></a>\n",
    "### SMR breakdown by care home status\n",
    "\n",
    "Monthly coding activity rates by care home status.  Care home status is defined using this  [NHS England Care Homes residential status codelist](https://codelists.opensafely.org/codelist/opensafely/nhs-england-care-homes-residential-status/3712ef13/)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "plot_measures(measures_df_care_home_status,\n",
    "              'SMR use by care home status per 1000',  'care_home_status_rates', 'num_per_thousand', category='care_home_status')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<a id='smr-hospital-admission'></a>\n",
    "### SMR breakdown by recent hospitalisation status\n",
    "\n",
    "Monthly coding activity rates by recent hospital admission.  Here we look at the rate of SMR in those that were discharged from hospital within the prior 3 months vs those that were not."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "plot_measures(measures_df_hospital_admission,\n",
    "              'SMR use by hospital_admission status per 1000',  'hospital_admission_rates', 'num_per_thousand', category='recent_hospital_admission')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<a id='smr-falls'></a>\n",
    "### SMR breakdown by recent fall status\n",
    "\n",
    "Monthly coding activity rates by recent fall status.  Here we look at the rate of SMR in those that had a recorded fall at any point within the prior 3 months vs those that did not."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "plot_measures(measures_df_falls,\n",
    "              'SMR use by falls status per 1000',  'falls_rates', 'num_per_thousand', category='recent_falls')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting ebmdatalab\n",
      "  Using cached ebmdatalab-0.0.22-py2.py3-none-any.whl (2.4 MB)\n",
      "Requirement already satisfied: pandas>=0.24 in /usr/local/Cellar/jupyterlab/3.0.5/libexec/lib/python3.9/site-packages (from ebmdatalab) (1.2.2)\n",
      "Collecting descartes\n",
      "  Using cached descartes-1.1.0-py3-none-any.whl (5.8 kB)\n",
      "Collecting pandas-gbq>=0.8.0\n",
      "  Using cached pandas_gbq-0.14.1-py3-none-any.whl (24 kB)\n",
      "Collecting geopandas\n",
      "  Using cached geopandas-0.8.2-py2.py3-none-any.whl (962 kB)\n",
      "Collecting statsmodels\n",
      "  Using cached statsmodels-0.12.2-cp39-cp39-macosx_10_15_x86_64.whl (9.6 MB)\n",
      "Collecting seaborn\n",
      "  Using cached seaborn-0.11.1-py3-none-any.whl (285 kB)\n",
      "Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/Cellar/jupyterlab/3.0.5/libexec/lib/python3.9/site-packages (from pandas>=0.24->ebmdatalab) (2.8.1)\n",
      "Requirement already satisfied: numpy>=1.16.5 in /usr/local/Cellar/jupyterlab/3.0.5/libexec/lib/python3.9/site-packages (from pandas>=0.24->ebmdatalab) (1.20.1)\n",
      "Requirement already satisfied: pytz>=2017.3 in /usr/local/Cellar/jupyterlab/3.0.5/libexec/lib/python3.9/site-packages (from pandas>=0.24->ebmdatalab) (2020.5)\n",
      "Collecting google-auth-oauthlib\n",
      "  Using cached google_auth_oauthlib-0.4.2-py2.py3-none-any.whl (18 kB)\n",
      "Collecting google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1\n",
      "  Using cached google_cloud_bigquery-2.10.0-py2.py3-none-any.whl (215 kB)\n",
      "Requirement already satisfied: setuptools in /usr/local/Cellar/jupyterlab/3.0.5/libexec/lib/python3.9/site-packages (from pandas-gbq>=0.8.0->ebmdatalab) (51.1.1)\n",
      "Collecting pydata-google-auth\n",
      "  Using cached pydata_google_auth-1.1.0-py2.py3-none-any.whl (13 kB)\n",
      "Collecting google-auth\n",
      "  Using cached google_auth-1.27.0-py2.py3-none-any.whl (135 kB)\n",
      "Collecting google-api-core[grpc]<2.0.0dev,>=1.23.0\n",
      "  Using cached google_api_core-1.26.0-py2.py3-none-any.whl (92 kB)\n",
      "Collecting google-resumable-media<2.0dev,>=0.6.0\n",
      "  Using cached google_resumable_media-1.2.0-py2.py3-none-any.whl (75 kB)\n",
      "Collecting google-cloud-core<2.0dev,>=1.4.1\n",
      "  Using cached google_cloud_core-1.6.0-py2.py3-none-any.whl (28 kB)\n",
      "Collecting protobuf>=3.12.0\n",
      "  Using cached protobuf-3.15.3-cp39-cp39-macosx_10_9_x86_64.whl (1.0 MB)\n",
      "Requirement already satisfied: packaging>=14.3 in /usr/local/Cellar/jupyterlab/3.0.5/libexec/lib/python3.9/site-packages (from google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas-gbq>=0.8.0->ebmdatalab) (20.8)\n",
      "Collecting proto-plus>=1.10.0\n",
      "  Using cached proto_plus-1.13.0-py3-none-any.whl\n",
      "Collecting pyarrow<4.0dev,>=1.0.0\n",
      "  Using cached pyarrow-3.0.0-cp39-cp39-macosx_10_13_x86_64.whl (14.2 MB)\n",
      "Collecting google-cloud-bigquery-storage<3.0.0dev,>=2.0.0\n",
      "  Using cached google_cloud_bigquery_storage-2.3.0-py2.py3-none-any.whl (142 kB)\n",
      "Collecting grpcio<2.0dev,>=1.32.0\n",
      "  Using cached grpcio-1.35.0-cp39-cp39-macosx_10_10_x86_64.whl (3.8 MB)\n",
      "Collecting googleapis-common-protos<2.0dev,>=1.6.0\n",
      "  Using cached googleapis_common_protos-1.53.0-py2.py3-none-any.whl (198 kB)\n",
      "Collecting requests<3.0.0dev,>=2.18.0\n",
      "  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)\n",
      "Requirement already satisfied: six>=1.13.0 in /usr/local/Cellar/jupyterlab/3.0.5/libexec/lib/python3.9/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.23.0->google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas-gbq>=0.8.0->ebmdatalab) (1.15.0)\n",
      "Collecting rsa<5,>=3.1.4\n",
      "  Using cached rsa-4.7.2-py3-none-any.whl (34 kB)\n",
      "Collecting pyasn1-modules>=0.2.1\n",
      "  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)\n",
      "Collecting cachetools<5.0,>=2.0.0\n",
      "  Using cached cachetools-4.2.1-py3-none-any.whl (12 kB)\n",
      "Collecting libcst>=0.2.5\n",
      "  Using cached libcst-0.3.17-py3-none-any.whl (507 kB)\n",
      "Collecting google-crc32c<2.0dev,>=1.0\n",
      "  Using cached google_crc32c-1.1.2-cp39-cp39-macosx_10_14_x86_64.whl (27 kB)\n",
      "Requirement already satisfied: cffi>=1.0.0 in /usr/local/Cellar/jupyterlab/3.0.5/libexec/lib/python3.9/site-packages (from google-crc32c<2.0dev,>=1.0->google-resumable-media<2.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas-gbq>=0.8.0->ebmdatalab) (1.14.4)\n",
      "Requirement already satisfied: pycparser in /usr/local/Cellar/jupyterlab/3.0.5/libexec/lib/python3.9/site-packages (from cffi>=1.0.0->google-crc32c<2.0dev,>=1.0->google-resumable-media<2.0dev,>=0.6.0->google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas-gbq>=0.8.0->ebmdatalab) (2.20)\n",
      "Collecting typing-extensions>=3.7.4.2\n",
      "  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)\n",
      "Collecting pyyaml>=5.2\n",
      "  Using cached PyYAML-5.4.1-cp39-cp39-macosx_10_9_x86_64.whl (259 kB)\n",
      "Collecting typing-inspect>=0.4.0\n",
      "  Using cached typing_inspect-0.6.0-py3-none-any.whl (8.1 kB)\n",
      "Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/Cellar/jupyterlab/3.0.5/libexec/lib/python3.9/site-packages (from packaging>=14.3->google-cloud-bigquery[bqstorage,pandas]<3.0.0dev,>=1.11.1->pandas-gbq>=0.8.0->ebmdatalab) (2.4.7)\n",
      "Collecting pyasn1<0.5.0,>=0.4.6\n",
      "  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)\n",
      "Collecting idna<3,>=2.5\n",
      "  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)\n",
      "Collecting urllib3<1.27,>=1.21.1\n",
      "  Using cached urllib3-1.26.3-py2.py3-none-any.whl (137 kB)\n",
      "Collecting certifi>=2017.4.17\n",
      "  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)\n",
      "Collecting chardet<5,>=3.0.2\n",
      "  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)\n",
      "Collecting mypy-extensions>=0.3.0\n",
      "  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)\n",
      "Requirement already satisfied: matplotlib in /usr/local/Cellar/jupyterlab/3.0.5/libexec/lib/python3.9/site-packages (from descartes->ebmdatalab) (3.3.4)\n",
      "Collecting fiona\n",
      "  Using cached Fiona-1.8.18.tar.gz (1.3 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_869ec939b0804f498b78e85cb88d5b72/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_869ec939b0804f498b78e85cb88d5b72/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-x1gzop6u\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_869ec939b0804f498b78e85cb88d5b72/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/9f/e8/401cdaa58d862a25c4b3365acf7d2bd7ac77191e3dc9acdcdac0eff20ff0/Fiona-1.8.18.tar.gz#sha256=b732ece0ff8886a29c439723a3e1fc382718804bb057519d537a81308854967a (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.17.tar.gz (1.3 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_78b570145688454aaa9d27196d27ea3a/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_78b570145688454aaa9d27196d27ea3a/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-lz13_5xx\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_78b570145688454aaa9d27196d27ea3a/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/88/62/69347ba2c41b526e1953c4cb66d51170b2869808863c03af202ba0121670/Fiona-1.8.17.tar.gz#sha256=716201c21246587f374785bec6d6a20a984fe1f6c2b0e83bf15127eb8f724d0c (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.16.tar.gz (1.3 MB)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_5ae6a86b541d4d5799f3002a802d2a04/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_5ae6a86b541d4d5799f3002a802d2a04/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-kz8hr_cg\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_5ae6a86b541d4d5799f3002a802d2a04/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/1e/60/dfc6115a11338d8aa96cacd8c60635223d9c97d61d556c90acc5dfd663fa/Fiona-1.8.16.tar.gz#sha256=fd6dfb65959becc916e9f6928618bfd59c16cdbc413ece0fbac61489cd11255f (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.15.tar.gz (1.3 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_a346f1345ed641d08fe325c4e2e06730/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_a346f1345ed641d08fe325c4e2e06730/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-434voqpb\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_a346f1345ed641d08fe325c4e2e06730/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/55/2f/17450ec2c8fcc720a8a3e4d9a383499508475c7cfb90f7eca9fb585ac598/Fiona-1.8.15.tar.gz#sha256=3b1c9b5c834fae2fe947cfaea176db890bc6750d1a6ba9f54d969c19ffcd191e (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.14.tar.gz (1.3 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_6ad3387b347845cfa7d5db326f992b4d/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_6ad3387b347845cfa7d5db326f992b4d/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-bpsij0kx\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_6ad3387b347845cfa7d5db326f992b4d/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/5c/fd/5ec54f2d9b3d5dd23dd443fad5630d6b872e2664814c68b856c47e0d65af/Fiona-1.8.14.tar.gz#sha256=6eac038206c89d2cf5f99ea38b81cc228dc21eac5f47870a9a32d453b0007f4d (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.13.post1.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_fde6026507f947269efdfade4838e176/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_fde6026507f947269efdfade4838e176/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-xluh1emo\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_fde6026507f947269efdfade4838e176/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/6d/42/f4a7cac53b28fa70e9a93d0e89a24d33e14826dad6644b699362ad84dde0/Fiona-1.8.13.post1.tar.gz#sha256=1a432bf9fd56f089256c010da009c90d4a795c531a848132c965052185336600 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.13.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_73c3661a578f48ea9e8fbd75bbd5c31b/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_73c3661a578f48ea9e8fbd75bbd5c31b/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-aysscui1\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_73c3661a578f48ea9e8fbd75bbd5c31b/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/be/04/31d0a6f03943b1684f32c9b861be40c1fd282468fa6bd54ddf4a774e6b0f/Fiona-1.8.13.tar.gz#sha256=5ec34898c8b983a723fb4e949dd3e0ed7e691c303e51f6bfd61e52ac9ac813ae (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.12.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_628b8a55f5ea42b5bdfe600fb294026f/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_628b8a55f5ea42b5bdfe600fb294026f/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-997wyj9q\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_628b8a55f5ea42b5bdfe600fb294026f/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/97/d8/feab39987296437fbdc3029fb39752a14355d217d73b93471010b8dd63a3/Fiona-1.8.12.tar.gz#sha256=c9266ddf6ae2a64fcea20014ddf27f800ac07584f2fdb09c2a02f3b3a52e371c (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  Using cached Fiona-1.8.11.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_956be984710d4134ab086d3c3ac57178/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_956be984710d4134ab086d3c3ac57178/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-kew3c9bw\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_956be984710d4134ab086d3c3ac57178/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/9d/f4/0a0ddc6174c4a93679b5f1dd3535e7ef8989828e6d5f86112de681f8c87b/Fiona-1.8.11.tar.gz#sha256=1e7ca9e051f5bffa1c43c70d573da9ca223fc076b84fa73380614fc02b9eb7f6 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.10.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_2e0207e4dd1a4657b75a0d4a64b47b2b/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_2e0207e4dd1a4657b75a0d4a64b47b2b/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-5ntgocbt\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_2e0207e4dd1a4657b75a0d4a64b47b2b/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/13/73/f80b491ed8559326fab202a6d6333a3cd6e8be1e9d782bc6c0d03d476457/Fiona-1.8.10.tar.gz#sha256=ff562eb2f3960e21f8c7f050ddd7f47a763869ea14afc2234a40df72666c6a2c (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.9.post2.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_3d18cc66f5f84718a747ac30156d0957/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_3d18cc66f5f84718a747ac30156d0957/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-0m49bej2\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_3d18cc66f5f84718a747ac30156d0957/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/9b/52/45e75507660ce0e86176d0f59b659560f687e2c7e9ebf82a10e7dcd2d3b7/Fiona-1.8.9.post2.tar.gz#sha256=210fb038b579fab38f35ddbdd31b9725f4d5099b3edfd4b87c983e5d47b79983 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.9.post1.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_abaefe1ca69044e7be23f41e0764a485/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_abaefe1ca69044e7be23f41e0764a485/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-18x0zy0b\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_abaefe1ca69044e7be23f41e0764a485/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/0e/a4/d9dd7399be809d3990f5000fb6ae43189ea26ae88be1bed3a4c9ddc1becc/Fiona-1.8.9.post1.tar.gz#sha256=d5e0ea0b8addffe9cba4cb59e2bd495b015230e7a1b1597974f5048211930199 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.9.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_10cdb5ffdfc1442589e0d10bb754b812/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_10cdb5ffdfc1442589e0d10bb754b812/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-cyk4s7vd\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_10cdb5ffdfc1442589e0d10bb754b812/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/ad/92/dcbd8c54d697c22f299b5af63b6df3acfbd06c6d72e249614c05be99337c/Fiona-1.8.9.tar.gz#sha256=4dd6e2f5327c1174143c7c8594a75d373bc72f2c9a2a6daee312c3186a128add (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.8.tar.gz (1.7 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_2dc57402595c43ac82eee77b5645e8ac/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_2dc57402595c43ac82eee77b5645e8ac/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-o16vcs4c\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_2dc57402595c43ac82eee77b5645e8ac/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/94/7f/e288db1ad63d759d494c30caae34f865e0c6927588c490705e91b7134193/Fiona-1.8.8.tar.gz#sha256=711c3be73203b37812992089445a1e4e9d3d6b64e667389f7b15406e15a91e83 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.7.tar.gz (1.7 MB)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_8db50053db4f493194844fe916626b82/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_8db50053db4f493194844fe916626b82/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-0dcfkxvv\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_8db50053db4f493194844fe916626b82/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/78/62/daafd070aebefa639df247705b97f13f7cfad43895581b5cae41bd886709/Fiona-1.8.7.tar.gz#sha256=a55a23615bad3e142d4e4cda97bb5de83c778a80049222e9dffae93c13b5cf93 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.6.tar.gz (1.7 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_7b108fe141254822860433e23374d3b8/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_7b108fe141254822860433e23374d3b8/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-zf_90op5\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_7b108fe141254822860433e23374d3b8/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/41/9d/63696e7b1de42aad294d4781199a408bec593d8fdb80a2b4a788c911a33b/Fiona-1.8.6.tar.gz#sha256=fa31dfe8855b9cd0b128b47a4df558f1b8eda90d2181bff1dd9854e5556efb3e (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.5.tar.gz (1.7 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_dc57c733b239419394f5ecbda69b4a91/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_dc57c733b239419394f5ecbda69b4a91/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-yi106nsz\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_dc57c733b239419394f5ecbda69b4a91/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/7b/af/1c2c83c4a8363a4ce9fea817b1910b5e071bed012e18257faa2a0ab3cfe7/Fiona-1.8.5.tar.gz#sha256=4f5cc2d449edbbf693c83e24cdada72de7c41297383d16fcc92387eb445e9d35 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.4.tar.gz (1.1 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_2bb61307ad064432b9d40cd8c4d8bb91/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_2bb61307ad064432b9d40cd8c4d8bb91/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-jeqjl_9s\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_2bb61307ad064432b9d40cd8c4d8bb91/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/3a/16/84960540e9fce61d767fd2f0f1d95f4c63e99ab5d8fddc308e8b51b059b8/Fiona-1.8.4.tar.gz#sha256=aec9ab2e3513c9503ec123b1a8573bee55fc6a66e2ac07088c3376bf6738a424 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.3.tar.gz (1.1 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_95024537e2f641739d40aeb0e79675d7/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_95024537e2f641739d40aeb0e79675d7/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-3fi0o2ml\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_95024537e2f641739d40aeb0e79675d7/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/46/d1/fcdb32513a03abfde0d97fd9782ce0f8cc0540fa6c6ce783e87b94064964/Fiona-1.8.3.tar.gz#sha256=3e831100a23c3b6cd32b98baf0c9e2119d909b44a5cf4533d3625f61dcf2d2b1 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.2.tar.gz (1.2 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_d0fe1e04865846f687e2cc59e8fe23c4/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_d0fe1e04865846f687e2cc59e8fe23c4/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-a94rvb8p\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_d0fe1e04865846f687e2cc59e8fe23c4/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/25/50/0466d5d83e1859c5ca38351ee932d64cc5635f9d4dad522879e58f4b0018/Fiona-1.8.2.tar.gz#sha256=4c6419b7ac29136708029f6a44b4ccd458735a4d241016c7b1bab41685c08d8f (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  Using cached Fiona-1.8.1.tar.gz (1.1 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_f42e8203407741c7ad66536d494e9c2b/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_f42e8203407741c7ad66536d494e9c2b/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-edq4dhr_\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_f42e8203407741c7ad66536d494e9c2b/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/3e/5f/0c6704efeea2ff3fba7f54cc6ec38070157f21bc1cffa7bdfa7c9f6b8f7a/Fiona-1.8.1.tar.gz#sha256=4c34bb4c5cd788aaf14e5484c3b7de407b1a8a7c7b2d29bbb2e8b37931e83b8d (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.8.0.tar.gz (1.4 MB)\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_e09661800f44435bbad7bb1a1200f717/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_e09661800f44435bbad7bb1a1200f717/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-pip-egg-info-gau_wewx\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_e09661800f44435bbad7bb1a1200f717/\n",
      "    Complete output (2 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/2a/bd/c1efc2680f338e5941121c776d6323af6b9698ac739e22ba523cee348a7f/Fiona-1.8.0.tar.gz#sha256=20141a9ece06daa7bb4333fba640c2fe39a49f8aca5492d1da8595d41e91844a (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "  Using cached Fiona-1.7.13.tar.gz (731 kB)\n",
      "Collecting pyproj>=2.2.0\n",
      "  Using cached pyproj-3.0.0.post1-cp39-cp39-macosx_10_9_x86_64.whl (7.4 MB)\n",
      "Collecting shapely\n",
      "  Using cached Shapely-1.7.1-cp39-cp39-macosx_10_9_x86_64.whl (1.0 MB)\n",
      "Collecting cligj>=0.4\n",
      "  Using cached cligj-0.7.1-py3-none-any.whl (7.1 kB)\n",
      "Collecting click-plugins\n",
      "  Using cached click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)\n",
      "Collecting munch\n",
      "  Using cached munch-2.5.0-py2.py3-none-any.whl (10 kB)\n",
      "Collecting click<8,>=4.0\n",
      "  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)\n",
      "Collecting requests-oauthlib>=0.7.0\n",
      "  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)\n",
      "Collecting oauthlib>=3.0.0\n",
      "  Using cached oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)\n",
      "Requirement already satisfied: pillow>=6.2.0 in /usr/local/Cellar/jupyterlab/3.0.5/libexec/lib/python3.9/site-packages (from matplotlib->descartes->ebmdatalab) (8.1.0)\n",
      "Requirement already satisfied: cycler>=0.10 in /usr/local/Cellar/jupyterlab/3.0.5/libexec/lib/python3.9/site-packages (from matplotlib->descartes->ebmdatalab) (0.10.0)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/Cellar/jupyterlab/3.0.5/libexec/lib/python3.9/site-packages (from matplotlib->descartes->ebmdatalab) (1.3.1)\n",
      "Collecting scipy>=1.0\n",
      "  Using cached scipy-1.6.1-cp39-cp39-macosx_10_9_x86_64.whl (30.9 MB)\n",
      "Collecting patsy>=0.5\n",
      "  Using cached patsy-0.5.1-py2.py3-none-any.whl (231 kB)\n",
      "Using legacy 'setup.py install' for fiona, since package 'wheel' is not installed.\n",
      "Installing collected packages: pyasn1, urllib3, rsa, pyasn1-modules, protobuf, idna, chardet, certifi, cachetools, typing-extensions, requests, mypy-extensions, googleapis-common-protos, google-auth, typing-inspect, pyyaml, oauthlib, grpcio, google-crc32c, google-api-core, requests-oauthlib, proto-plus, libcst, google-resumable-media, google-cloud-core, click, pyarrow, munch, google-cloud-bigquery-storage, google-cloud-bigquery, google-auth-oauthlib, cligj, click-plugins, shapely, scipy, pyproj, pydata-google-auth, patsy, fiona, statsmodels, seaborn, pandas-gbq, geopandas, descartes, ebmdatalab\n",
      "  Attempting uninstall: idna\n",
      "    Found existing installation: idna 3.1\n",
      "    Uninstalling idna-3.1:\n",
      "      Successfully uninstalled idna-3.1\n",
      "  Attempting uninstall: requests\n",
      "    Found existing installation: requests 2.15.1\n",
      "    Uninstalling requests-2.15.1:\n",
      "      Successfully uninstalled requests-2.15.1\n",
      "    Running setup.py install for fiona ... \u001b[?25lerror\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_50000dd8fd2c4cc9837a5c1d0d5885ea/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_50000dd8fd2c4cc9837a5c1d0d5885ea/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-record-r8tiy50u/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/jupyterlab/3.0.5/libexec/include/site/python3.9/fiona\n",
      "         cwd: /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_50000dd8fd2c4cc9837a5c1d0d5885ea/\n",
      "    Complete output (50 lines):\n",
      "    Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'\n",
      "    /usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'metadata_version'\n",
      "      warnings.warn(msg)\n",
      "    /usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'requires_python'\n",
      "      warnings.warn(msg)\n",
      "    /usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'requires_external'\n",
      "      warnings.warn(msg)\n",
      "    running install\n",
      "    running build\n",
      "    running build_py\n",
      "    creating build\n",
      "    creating build/lib.macosx-10.15-x86_64-3.9\n",
      "    creating build/lib.macosx-10.15-x86_64-3.9/fiona\n",
      "    copying ./fiona/compat.py -> build/lib.macosx-10.15-x86_64-3.9/fiona\n",
      "    copying ./fiona/drvsupport.py -> build/lib.macosx-10.15-x86_64-3.9/fiona\n",
      "    copying ./fiona/inspector.py -> build/lib.macosx-10.15-x86_64-3.9/fiona\n",
      "    copying ./fiona/__init__.py -> build/lib.macosx-10.15-x86_64-3.9/fiona\n",
      "    copying ./fiona/crs.py -> build/lib.macosx-10.15-x86_64-3.9/fiona\n",
      "    copying ./fiona/rfc3339.py -> build/lib.macosx-10.15-x86_64-3.9/fiona\n",
      "    copying ./fiona/transform.py -> build/lib.macosx-10.15-x86_64-3.9/fiona\n",
      "    copying ./fiona/collection.py -> build/lib.macosx-10.15-x86_64-3.9/fiona\n",
      "    copying ./fiona/errors.py -> build/lib.macosx-10.15-x86_64-3.9/fiona\n",
      "    copying ./fiona/tool.py -> build/lib.macosx-10.15-x86_64-3.9/fiona\n",
      "    creating build/lib.macosx-10.15-x86_64-3.9/fiona/fio\n",
      "    copying ./fiona/fio/options.py -> build/lib.macosx-10.15-x86_64-3.9/fiona/fio\n",
      "    copying ./fiona/fio/collect.py -> build/lib.macosx-10.15-x86_64-3.9/fiona/fio\n",
      "    copying ./fiona/fio/distrib.py -> build/lib.macosx-10.15-x86_64-3.9/fiona/fio\n",
      "    copying ./fiona/fio/env.py -> build/lib.macosx-10.15-x86_64-3.9/fiona/fio\n",
      "    copying ./fiona/fio/insp.py -> build/lib.macosx-10.15-x86_64-3.9/fiona/fio\n",
      "    copying ./fiona/fio/cat.py -> build/lib.macosx-10.15-x86_64-3.9/fiona/fio\n",
      "    copying ./fiona/fio/__init__.py -> build/lib.macosx-10.15-x86_64-3.9/fiona/fio\n",
      "    copying ./fiona/fio/ls.py -> build/lib.macosx-10.15-x86_64-3.9/fiona/fio\n",
      "    copying ./fiona/fio/dump.py -> build/lib.macosx-10.15-x86_64-3.9/fiona/fio\n",
      "    copying ./fiona/fio/calc.py -> build/lib.macosx-10.15-x86_64-3.9/fiona/fio\n",
      "    copying ./fiona/fio/filter.py -> build/lib.macosx-10.15-x86_64-3.9/fiona/fio\n",
      "    copying ./fiona/fio/load.py -> build/lib.macosx-10.15-x86_64-3.9/fiona/fio\n",
      "    copying ./fiona/fio/main.py -> build/lib.macosx-10.15-x86_64-3.9/fiona/fio\n",
      "    copying ./fiona/fio/info.py -> build/lib.macosx-10.15-x86_64-3.9/fiona/fio\n",
      "    copying ./fiona/fio/helpers.py -> build/lib.macosx-10.15-x86_64-3.9/fiona/fio\n",
      "    copying ./fiona/fio/bounds.py -> build/lib.macosx-10.15-x86_64-3.9/fiona/fio\n",
      "    running build_ext\n",
      "    building 'fiona._transform' extension\n",
      "    creating build/temp.macosx-10.15-x86_64-3.9\n",
      "    creating build/temp.macosx-10.15-x86_64-3.9/fiona\n",
      "    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/include -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/tcl-tk/include -I/usr/local/Cellar/jupyterlab/3.0.5/libexec/include -I/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c fiona/_transform.cpp -o build/temp.macosx-10.15-x86_64-3.9/fiona/_transform.o\n",
      "    fiona/_transform.cpp:606:10: fatal error: 'cpl_conv.h' file not found\n",
      "    #include \"cpl_conv.h\"\n",
      "             ^~~~~~~~~~~~\n",
      "    1 error generated.\n",
      "    error: command '/usr/bin/clang' failed with exit code 1\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[31mERROR: Command errored out with exit status 1: /usr/local/Cellar/jupyterlab/3.0.5/libexec/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_50000dd8fd2c4cc9837a5c1d0d5885ea/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-install-4kb8e64v/fiona_50000dd8fd2c4cc9837a5c1d0d5885ea/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /private/var/folders/yv/v59h6nvx7fjfp3pzwyx546x40000gn/T/pip-record-r8tiy50u/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/jupyterlab/3.0.5/libexec/include/site/python3.9/fiona Check the logs for full command output.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[?25hNote: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install ebmdatalab\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
